### ISSUE TITLE
Experiment

### ISSUE THREAD

**Issue by Shashank8624** [Shashank8624/School-Parent-App#1]
To enhance the styling of your registration page, you can use CSS to create a visually appealing form. I'll provide a complete example, including both the JSX and CSS styling. 

### Step 1: Update Your React Component

Modify your `ParentRegistrationForm` component to include class names for styling:

```jsx
import React, { useState } from 'react';
import axios from 'axios';
import './ParentRegistrationForm.css'; // Import your CSS file

const ParentRegistrationForm = () => {
    const [formData, setFormData] = useState({
        ParentName: '',
        StudentName: '',
        StudentRegisterNumber: '',
        Address: '',
        State: '',
        Country: '',
        City: '',
        ZipCode: '',
        EmailAddress: '',
        PrimaryContactPerson: '',
        PrimaryContactPersonMobile: '',
        SecondaryContactPerson: '',
        SecondaryContactPersonMobile: '',
        Status: ''
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prevState => ({
            ...prevState,
            [name]: value
        }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('https://localhost:7183/api/Parents', formData);

            console.log(response.data);
            alert('Registration successful');
        } catch (error) {
            console.error('Registration Failed', error.response?.data || error.message);
            alert('There was an error registering the parent!');
        }
    };

    return (
        <div className="form-container">
            <h2>Parent Registration Form</h2>
            <form onSubmit={handleSubmit} className="registration-form">
                <input type="text" name="ParentName" value={formData.ParentName} onChange={handleChange} placeholder="Parent Name" className="form-input" />
                <input type="text" name="StudentName" value={formData.StudentName} onChange={handleChange} placeholder="Student Name" className="form-input" />
                <input type="text" name="StudentRegisterNumber" value={formData.StudentRegisterNumber} onChange={handleChange} placeholder="Student Register Number" className="form-input" />
                <input type="text" name="Address" value={formData.Address} onChange={handleChange} placeholder="Address" className="form-input" />
                <input type="text" name="State" value={formData.State} onChange={handleChange} placeholder="State" className="form-input" />
                <input type="text" name="Country" value={formData.Country} onChange={handleChange} placeholder="Country" className="form-input" />
                <input type="text" name="City" value={formData.City} onChange={handleChange} placeholder="City" className="form-input" />
                <input type="text" name="ZipCode" value={formData.ZipCode} onChange={handleChange} placeholder="Zip Code" className="form-input" />
                <input type="email" name="EmailAddress" value={formData.EmailAddress} onChange={handleChange} placeholder="Email Address" className="form-input" />
                <input type="text" name="PrimaryContactPerson" value={formData.PrimaryContactPerson} onChange={handleChange} placeholder="Primary Contact Person" className="form-input" />
                <input type="text" name="PrimaryContactPersonMobile" value={formData.PrimaryContactPersonMobile} onChange={handleChange} placeholder="Primary Contact Person Mobile" className="form-input" />
                <input type="text" name="SecondaryContactPerson" value={formData.SecondaryContactPerson} onChange={handleChange} placeholder="Secondary Contact Person" className="form-input" />
                <input type="text" name="SecondaryContactPersonMobile" value={formData.SecondaryContactPersonMobile} onChange={handleChange} placeholder="Secondary Contact Person Mobile" className="form-input" />
                <input type="text" name="Status" value={formData.Status} onChange={handleChange} placeholder="Status" className="form-input" />

                <button type="submit" className="form-button">Register</button>
            </form>
        </div>
    );
};

export default ParentRegistrationForm;
```

### Step 2: Add CSS Styling

Create a `ParentRegistrationForm.css` file and add the following styles:

```css
/* ParentRegistrationForm.css */
.form-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 20px;
    background-color: #f7f9fc;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    max-width: 500px;
    margin: 40px auto;
}

.form-container h2 {
    margin-bottom: 20px;
    color: #333;
}

.registration-form {
    display: flex;
    flex-direction: column;
    width: 100%;
}

.form-input {
    padding: 10px;
    margin: 8px 0;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 16px;
}

.form-input:focus {
    border-color: #007BFF;
    outline: none;
    box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
}

.form-button {
    padding: 10px;
    margin-top: 20px;
    border: none;
    border-radius: 5px;
    background-color: #007BFF;
    color: white;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.form-button:hover {
    background-color: #0056b3;
}
```

### Explanation

1. **Container Styling**: The `.form-container` class styles the main container of the form. It centers the form, adds padding, background color, rounded corners, and a subtle box shadow.
2. **Form Styling**: The `registration-form` class ensures the form inputs are displayed in a column layout.
3. **Input Styling**: The `.form-input` class styles the text inputs with padding, margin, border, and rounded corners. The `:focus` pseudo-class adds a blue border and shadow effect when an input is focused.
4. **Button Styling**: The `.form-button` class styles the submit button with padding, border removal, background color, white text, rounded corners, and a hover effect that darkens the button color.

This styling creates a modern, clean look for your registration form, enhancing user experience and visual appeal.
